databases:
  - name: askbybook-db
    databaseName: askbybook_db
    user: askbybook_db_user

services:
  - type: web
    name: askmybook
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: askmybook
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: RESEMBLE_API_KEY
        sync: false
